/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as RegisterImport } from './routes/register';
import { Route as PrivacyPolicyImport } from './routes/privacy-policy';
import { Route as LoginImport } from './routes/login';
import { Route as ProtectImport } from './routes/_protect';
import { Route as IndexImport } from './routes/index';
import { Route as ProtectSecretImport } from './routes/_protect/secret';

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute
} as any);

const PrivacyPolicyRoute = PrivacyPolicyImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRoute
} as any);

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute
} as any);

const ProtectRoute = ProtectImport.update({
  id: '/_protect',
  getParentRoute: () => rootRoute
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute
} as any);

const ProtectSecretRoute = ProtectSecretImport.update({
  id: '/secret',
  path: '/secret',
  getParentRoute: () => ProtectRoute
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_protect': {
      id: '/_protect';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof ProtectImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/privacy-policy': {
      id: '/privacy-policy';
      path: '/privacy-policy';
      fullPath: '/privacy-policy';
      preLoaderRoute: typeof PrivacyPolicyImport;
      parentRoute: typeof rootRoute;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterImport;
      parentRoute: typeof rootRoute;
    };
    '/_protect/secret': {
      id: '/_protect/secret';
      path: '/secret';
      fullPath: '/secret';
      preLoaderRoute: typeof ProtectSecretImport;
      parentRoute: typeof ProtectImport;
    };
  }
}

// Create and export the route tree

interface ProtectRouteChildren {
  ProtectSecretRoute: typeof ProtectSecretRoute;
}

const ProtectRouteChildren: ProtectRouteChildren = {
  ProtectSecretRoute: ProtectSecretRoute
};

const ProtectRouteWithChildren = ProtectRoute._addFileChildren(ProtectRouteChildren);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '': typeof ProtectRouteWithChildren;
  '/login': typeof LoginRoute;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/register': typeof RegisterRoute;
  '/secret': typeof ProtectSecretRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '': typeof ProtectRouteWithChildren;
  '/login': typeof LoginRoute;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/register': typeof RegisterRoute;
  '/secret': typeof ProtectSecretRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/_protect': typeof ProtectRouteWithChildren;
  '/login': typeof LoginRoute;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/register': typeof RegisterRoute;
  '/_protect/secret': typeof ProtectSecretRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '' | '/login' | '/privacy-policy' | '/register' | '/secret';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '' | '/login' | '/privacy-policy' | '/register' | '/secret';
  id: '__root__' | '/' | '/_protect' | '/login' | '/privacy-policy' | '/register' | '/_protect/secret';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ProtectRoute: typeof ProtectRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute;
  RegisterRoute: typeof RegisterRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectRoute: ProtectRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_protect",
        "/login",
        "/privacy-policy",
        "/register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_protect": {
      "filePath": "_protect.tsx",
      "children": [
        "/_protect/secret"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/privacy-policy": {
      "filePath": "privacy-policy.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/_protect/secret": {
      "filePath": "_protect/secret.tsx",
      "parent": "/_protect"
    }
  }
}
ROUTE_MANIFEST_END */
